### ISSUE TITLE
Avaliação do PIM

### ISSUE THREAD

**Issue by Cassiano-Gunji** [MaluLopeS/AutoPlay#1]
É um prazer avaliar um trabalho de tamanha qualidade. Parabéns! Espero que permitam que eu utilize o trabalho de vocês como exemplo para os próximos alunos.

**Comment by malu-ls** [comment]
Boa noite professor, 
Claro que pode, nos sentimos muito honrados com o seu reconhecimento.
Obrigada por toda orientação!
